#!/bin/bash -e

LOCKFILE=~/."${0##*/}".lock
ARMBASE=/srv/data/http/0x1b.io/mirror/archlinux/arm
ARCBASE=/srv/data/http/0x1b.io/mirror/archlinux/archive/repos

[[ $1 != "" && ${1:0:1} != / ]] && { echo 'Absolute path please, ln is bugged'; exit 1; }

# we lock!
exec 9> "$LOCKFILE"
flock -n 9 || { echo 'Locking Failed' >&2; exit 1; }

# nice umask
umask 022

cd "$ARMBASE"

# update last
ln -svrnf "$(ls -1d "$ARCBASE"/*/*/*|sort|tail -n1)" last

# update last week
ln -srvnf "$ARCBASE/$(date -d 'last monday' +%Y/%m/%d)" week

# update last month
ln -srvnf "$ARCBASE/$(date +%Y/%m/01)" month

# vim:set sw=2 ts=2 ft=sh et:
