#!/bin/bash -e

# Copyright © Sébastien Luttringer
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

LOCKFILE=~/."${0##*/}".lock
ARMBASE=/srv/data/http/mirror.6502.ws/archlinux/arm
ARCBASE=/srv/data/http/mirror.6502.ws/archlinux/archive/repos

[[ $1 != "" && ${1:0:1} != / ]] && { echo 'Absolute path please, ln is bugged'; exit 1; }

[[ -t 1 ]] && set -x

# we lock!
exec 9> "$LOCKFILE"
flock -n 9 || { echo 'Locking Failed' >&2; exit 1; }

# nice umask
umask 022

cd "$ARMBASE"

# update last
ln -svrnf "$(ls -1d "$ARCBASE"/*/*/*|sort|tail -n1)" last

# update last week
ln -srvnf "$ARCBASE/$(date -d 'last monday' +%Y/%m/%d)" week

# update last month
ln -srvnf "$ARCBASE/$(date +%Y/%m/01)" month

# vim:set sw=2 ts=2 ft=sh et:
