#!/bin/bash -e

# Copyright © Sébastien Luttringer
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

[[ -t 1 ]] && set -x

UPSTREAM='rsync://rsync.archlinux.org/ftp_tier1/iso/'
LOCKFILE=~/."${0##*/}".lock
BASE=/srv/ftp/archlinux/archive/iso
SNAPR="$(date +%Y/%m/%d)"
SNAP="$BASE/$SNAPR"

# we lock!
exec 9> "$LOCKFILE"
flock -n 9 || { echo 'Locking Failed' >&2; exit 1; }

# nice umask
umask 022

# ensure destination exists
[[ -d $BASE ]] || mkdir -p "$BASE"

# Rsync from master using last sync
rsync -vrltH "$UPSTREAM" --include='/????.??.??/***' --exclude='*' "$BASE/"

# vim:set sw=2 ts=2 ft=sh et:
