#!/bin/bash -e

[[ -t 1 ]] && set -x

UPSTREAM='rsync://mirror.pkgbuild.com/packages/'
LOCKFILE=~/."${0##*/}".lock
BASE=/srv/data/http/mirror.6502.ws/archlinux/archive/repos
SNAPR="$(date +%Y/%m/%d)"
SNAP="$BASE/$SNAPR"

# we lock!
exec 9> "$LOCKFILE"
flock -n 9 || { echo 'Locking Failed' >&2; exit 1; }

# nice umask
umask 022

# ensure destination exists
[[ -d $SNAP ]] || mkdir -p "$SNAP"

# compute last but today
LAST="$(ls -1d $BASE/*/*/*|sort|grep -v $SNAPR|tail -n1)"

# display info
echo starting rsync
echo   snapshot is: $SNAP
echo   last is: $LAST

[[ -n $LAST ]] && LINKDEST="--link-dest=$LAST/"

# Rsync from master using last sync
# We must use absolute path with --link-dest to avoid errors
rsync  -rltvH $LINKDEST --exclude '*/.*' --exclude '*/os/i686' --exclude 'pool/*/*-i686.pkg.tar.xz' --exclude 'pool/*/*-i686.pkg.tar.xz.sig' --exclude 'pool/*/*-i686.pkg.tar.gz' "$UPSTREAM" "$SNAP/"

# only to have a quick check of sync in listdir
touch "$SNAP"

# vim:set sw=2 ts=2 ft=sh et:
