#!/bin/bash -e

# Copyright © Sébastien Luttringer
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

[[ -t 1 ]] && set -x

UPSTREAM='rsync://pkgbuild.com/packages/'
LOCKFILE=~/."${0##*/}".lock
BASE=/srv/ftp/archlinux/archive/repos
SNAPR="$(date +%Y/%m/%d)"
SNAP="$BASE/$SNAPR"

# we lock!
exec 9> "$LOCKFILE"
flock -n 9 || { echo 'Locking Failed' >&2; exit 1; }

# nice umask
umask 022

# ensure destination exists
[[ -d $SNAP ]] || mkdir -p "$SNAP"

# compute last but today
LAST="$(ls -1d "$BASE"/*/*/*|sort|grep -v $SNAPR|tail -n1)"

# display info
echo starting rsync
echo   snapshot is: $SNAP
echo   last is: $LAST

[[ -n $LAST ]] && LINKDEST="--link-dest=$LAST/"

# Rsync from master using last sync
# We must use absolute path with --link-dest to avoid errors
rsync  -rltH "$LINKDEST" --exclude '*/.*' "$UPSTREAM" "$SNAP/"

# only to have a quick check of sync in listdir
touch "$SNAP"

# vim:set sw=2 ts=2 ft=sh et:
