#!/bin/bash

CMDPATH=`realpath ${0}`
echo $CMDPATH

BASEPATH=`dirname ${CMDPATH}`
echo $BASEPATH

echo "Sync repository:"
${BASEPATH}/repo-rsync

echo "Package links:"
${BASEPATH}/package-links

echo "Iso Fetch:"
${BASEPATH}/iso-fetch

echo "Arm Links:"
${BASEPATH}/arm-link
